[target.'cfg(target_os = "linux")']
linker = "scripts/linux/mold-linker.sh"

[target.x86_64-pc-windows-msvc]
linker = "scripts/windows/windows-lld-linker.cmd"

[target.aarch64-pc-windows-msvc]
linker = "scripts/windows/windows-lld-linker.cmd"

[target.'cfg(target_arch = "x86_64")']
rustflags = ["-Ctarget-cpu=x86-64-v3"]
