//! The kit's icon set, served under `icons/` and `icons/file_icons/`.
//!
//! A host serves its own artwork first and falls back to [`KitAssets`].

use gpui::{AssetSource, Result, SharedString};
use std::borrow::Cow;

// `icon_bytes()`/`ICON_ASSETS` and `file_icon_bytes()`/`FILE_ICON_ASSETS`,
// generated by `build.rs` from `assets/icons/*.svg` and
// `assets/icons/file_icons/*.svg`.
include!(concat!(env!("OUT_DIR"), "/icons_assets.rs"));

/// Every icon path the kit serves, for hosts that list their own assets.
pub fn icon_paths() -> impl Iterator<Item = &'static str> {
    ICON_ASSETS.iter().chain(FILE_ICON_ASSETS.iter()).copied()
}

pub struct KitAssets;

impl KitAssets {
    pub fn load_static(path: &str) -> Option<Cow<'static, [u8]>> {
        icon_bytes(path)
            .or_else(|| file_icon_bytes(path))
            .map(Cow::Borrowed)
    }

    /// Lists `dir`. GPUI's registry lists only `""` and does not recurse, so
    /// the root holds every file.
    pub fn list_static(dir: &str) -> Vec<SharedString> {
        match dir.trim_end_matches('/') {
            "" => icon_paths().map(SharedString::from).collect(),
            "icons" => ICON_ASSETS
                .iter()
                .map(|path| SharedString::from(*path))
                .chain(std::iter::once("icons/file_icons".into()))
                .collect(),
            "icons/file_icons" => FILE_ICON_ASSETS
                .iter()
                .map(|path| SharedString::from(*path))
                .collect(),
            _ => vec![],
        }
    }
}

impl AssetSource for KitAssets {
    fn load(&self, path: &str) -> Result<Option<Cow<'static, [u8]>>> {
        Ok(Self::load_static(path))
    }

    fn list(&self, path: &str) -> Result<Vec<SharedString>> {
        Ok(Self::list_static(path))
    }
}

#[cfg(test)]
mod tests {
    use super::{FILE_ICON_ASSETS, ICON_ASSETS, KitAssets};
    use std::collections::BTreeSet;
    use std::path::Path;

    fn on_disk(dir: &Path, prefix: &str) -> BTreeSet<String> {
        std::fs::read_dir(dir)
            .expect("icon asset directory")
            .map(|entry| {
                format!(
                    "{prefix}/{}",
                    entry.expect("entry").file_name().to_string_lossy()
                )
            })
            .collect()
    }

    #[test]
    fn every_icon_on_disk_is_registered_and_loadable() {
        let icons_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/icons");
        let registered: BTreeSet<String> = KitAssets::list_static("icons")
            .into_iter()
            .map(|path| path.to_string())
            .collect();
        assert_eq!(registered, on_disk(&icons_dir, "icons"));
        let file_icons: BTreeSet<String> = KitAssets::list_static("icons/file_icons")
            .into_iter()
            .map(|path| path.to_string())
            .collect();
        assert_eq!(
            file_icons,
            on_disk(&icons_dir.join("file_icons"), "icons/file_icons")
        );
        for path in ICON_ASSETS.iter().chain(FILE_ICON_ASSETS.iter()) {
            assert!(KitAssets::load_static(path).is_some(), "{path}");
        }
    }
}
